// <auto-generated />
using System;
using DescartesDiffApi.Model.v1;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DescartesDiffApi.Migrations
{
    [DbContext(typeof(ApiContext))]
    partial class ApiContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("DescartesDiffApi.Model.v1.ValueToDiff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Data")
                        .HasColumnType("BLOB");

                    b.Property<string>("Direction")
                        .HasColumnType("TEXT");

                    b.Property<int>("ValueId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ValueToDiffs");
                });
#pragma warning restore 612, 618
        }
    }
}
